format = "$username$hostname$directory$git_branch$character"

[username]
show_always = true
style_user = "bold blue"
format = "[$user]($style) "

[hostname]
ssh_only = false
format = "@[$hostname](bold magenta) "

[directory]
style = "bold cyan"
truncation_length = 3

[character]
success_symbol = "➜ "
error_symbol = "➜ "

[python]
symbol = "🐍 "
pyenv_version_name = true
python_binary = ["python3", "python"]
detect_extensions = ["py"]
detect_files = [".python-version", "requirements.txt", "pyproject.toml", "setup.py"]
# This ensures it shows up if the virtual env is active:
format = 'via [${symbol}${version}]($style)' 
