format = "$username$hostname$directory$git_branch$character"
[username]
show_always = true
style_user = "bold blue"
format = "[$user]($style) "
[hostname]
ssh_only = false
format = "@[$hostname](bold magenta) "
[directory]
style = "bold cyan"
[character]
success_symbol = "➜ "
error_symbol = "➜ "
